version: 2
jobs:
  build:
    docker:
      - image: elixir:1.6
      - image: redis:3.2.8
    working_directory: /app
    environment:
      - MIX_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "mix.lock" }}
            - v1-deps-
      - restore_cache:
          key: v1-build
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test
      - save_cache:
          key: v1-deps-{{ checksum "mix.lock" }}
          paths:
            - /app/deps
      - save_cache:
          key: v1-build
          paths:
            - /app/_build
